#!/usr/bin/env bash
# Reconstructs the three harness source revisions used during profiling, rebuilds every variant in a
# temporary directory, and checks them against the archived artifacts (if the local archive exists),
# against each other (function level), and by the inputs each revision generates.
# Usage (from the repository root): bash docs/evidence/2026-10-09-profiling/harness/provenance_audit.sh [archive-dir]
# Writes only to a temporary directory. Requires Apple Clang, otool, c++filt, patch, python3.
# PROFILING_SOURCE_DIR selects an extracted measured engine source tree; default is the checkout.
set -euo pipefail
repo="$(pwd)"; here="$repo/docs/evidence/2026-10-09-profiling/harness"
engine_source="${PROFILING_SOURCE_DIR:-$repo}"
archive="${1:-$repo/benchmark_results/20261009T060102Z-phase3-profiling}"
t="$(mktemp -d)"; trap 'rm -rf "$t"' EXIT
mkdir -p "$t/rev1" "$t/rev2" "$t/rev3"
cp "$here/prof_harness.cpp" "$t/rev3/"
cp "$t/rev3/prof_harness.cpp" "$t/rev2/"; patch -s -R "$t/rev2/prof_harness.cpp" "$here/rev2-to-rev3.patch"
cp "$t/rev2/prof_harness.cpp" "$t/rev1/"; patch -s -R "$t/rev1/prof_harness.cpp" "$here/rev1-to-rev2.patch"
echo "Harness source SHA-256: rev1 $(shasum -a 256 "$t/rev1/prof_harness.cpp" | cut -c1-16)…  rev2 $(shasum -a 256 "$t/rev2/prof_harness.cpp" | cut -c1-16)…  rev3 $(shasum -a 256 "$t/rev3/prof_harness.cpp" | cut -c1-16)… (rev3 = published harness)"
for rev in rev1 rev2 rev3; do
  for v in timing:"" rusage:-DUSE_RUSAGE alloc:-DCOUNT_ALLOCS pcsamp:-DPC_SAMPLE; do
    # Same flags as the recorded harness/build.sh (absolute paths do not affect the output).
    /usr/bin/clang++ -std=c++20 -O3 -DNDEBUG -march=native -flto -Wall -Wextra -I"$engine_source/include" -I"$engine_source/benchmarks" \
      ${v#*:} "$engine_source/src/order_pool.cpp" "$engine_source/src/price_level.cpp" "$t/$rev/prof_harness.cpp" -o "$t/$rev/prof_${v%%:*}"
    otool -tvV "$t/$rev/prof_${v%%:*}" | tail -n +2 > "$t/${rev}_${v%%:*}.asm"
  done
done
echo
echo "== Rebuilt rev3 vs archived final binaries (archive: $archive)"
if [[ -d "$archive/harness" ]]; then
  for v in timing rusage alloc pcsamp; do
    a=$(shasum -a 256 "$archive/harness/prof_$v" | cut -d' ' -f1); b=$(shasum -a 256 "$t/rev3/prof_$v" | cut -d' ' -f1)
    echo "prof_$v: archived $a rebuilt $b $([[ $a == "$b" ]] && echo MATCH || echo DIFFER)"
  done
  echo "== Rebuilt rev1 prof_timing vs archived first-build disassembly (prof_timing.asm.txt, written 17:16:06 before any measurement)"
  if cmp -s <(tail -n +2 "$archive/prof_timing.asm.txt") "$t/rev1_timing.asm"; then echo "IDENTICAL ($(wc -l < "$t/rev1_timing.asm" | tr -d ' ') instruction lines, addresses included)"; else echo DIFFERENT; fi
else
  echo "archive not present: binary comparisons skipped (recorded results are in provenance-audit.txt)"
fi
echo
echo "== Function-level differences between revisions (function-relative offsets kept; hex addresses, adrp pages and"
echo "   constant-pool page offsets normalized)"
python3 -I - "$t" <<'PY'
import re, subprocess, sys, pathlib
t = pathlib.Path(sys.argv[1])
def funcs(p):
    out, cur, base = {}, None, None
    for l in p.read_text().splitlines():
        if not re.match(r"^[0-9a-f]{16}\s", l): cur = l.rstrip(":"); out[cur] = []; base = None; continue
        a = int(l.split()[0], 16); base = a if base is None else base
        ins = re.sub(r"0x[0-9a-f]+", "A", l[17:]); ins = re.sub(r"^adrp\t(\w+), \d+", r"adrp\t\1, PAGE", ins)
        ins = re.sub(r"\[(x\d+), #A\]", r"[\1]", ins)
        out[cur].append((a - base, ins))
    return out
dm = lambda n: subprocess.run(["c++filt", "-_", n], capture_output=True, text=True).stdout.strip()
timed = {"__ZN9OrderBookIPFvRK5TradeEE13addLimitOrderE4Sidejjyy", "__ZN11AddWorkload5batchER5Accum", "__ZN13MatchWorkload5batchER5Accum",
         "__ZN14CancelWorkload5batchER5Accum", "__ZN15PartialWorkload5batchER5Accum", "__ZN13SweepWorkload5batchER5Accum"}
for v in ("timing", "rusage", "alloc", "pcsamp"):
    for a, b in (("rev1", "rev2"), ("rev2", "rev3")):
        fa, fb = funcs(t / f"{a}_{v}.asm"), funcs(t / f"{b}_{v}.asm")
        ch = sorted(n for n in fa.keys() | fb.keys() if fa.get(n) != fb.get(n))
        print(f"prof_{v} {a}->{b}: {len(ch)}/{len(fb)} differ: " + "; ".join(dm(n) for n in ch))
        print(f"   timed functions (engine addLimitOrder, all Workload::batch) unchanged: {not (timed & set(ch))}")
PY
echo
echo "== Inputs generated by each revision's levelsK constructor (FNV-1a over side, price, quantity, id, participant)"
for rev in rev1 rev2 rev3; do
  if [[ $rev == rev1 ]]; then ctor='AddWorkload a(10000, k);'; extra='';
  else ctor='AddWorkload a(10000, k, true);'
    extra='AddWorkload arch(10000), gen(10000, 10, true); bool same = arch.in.size() == gen.in.size();
    for (size_t i = 0; same && i < arch.in.size(); ++i) { const auto &x = arch.in[i], &y = gen.in[i];
      same = x.side == y.side && y.price == x.price + 9910u && x.quantity == y.quantity && x.id == y.id && x.participantId == y.participantId; }
    std::printf("%s: archived add/10000 inputs vs generic K=10 inputs: %s\n", REV, same ? "identical except a constant +9910 price offset per side" : "DIFFERENT");'; fi
  cat > "$t/probe_$rev.cpp" <<CPP
#define main harness_main
#include "$t/$rev/prof_harness.cpp"
#undef main
#include <cstdio>
#define REV "$rev"
int main() {
    for (uint32_t k : {1u, 2u, 3u, 4u, 6u, 8u, 10u, 12u, 16u, 24u, 32u, 48u, 64u, 96u, 128u, 256u, 512u, 1024u, 2048u}) {
        $ctor
        uint64_t h = 1469598103934665603ull;
        auto mix = [&](uint64_t v) { h = (h ^ v) * 1099511628211ull; };
        for (auto& o : a.in) { mix(uint64_t(o.side)); mix(o.price); mix(o.quantity); mix(o.id); mix(o.participantId); }
        std::printf("%s K=%u name=%s hash=%016llx\n", REV, k, a.name(), (unsigned long long)h);
    }
    $extra
}
CPP
  /usr/bin/clang++ -std=c++20 -O1 -DNDEBUG -w -I"$engine_source/include" -I"$engine_source/benchmarks" "$engine_source/src/order_pool.cpp" "$engine_source/src/price_level.cpp" "$t/probe_$rev.cpp" -o "$t/probe_$rev"
  "$t/probe_$rev" > "$t/probe_$rev.out"
done
python3 -I - "$t" <<'PY'
import re, sys, pathlib
t = pathlib.Path(sys.argv[1]); rows = {}
for rev in ("rev1", "rev2", "rev3"):
    for k, name, h in re.findall(r"K=(\d+) name=(\S+) hash=(\w+)", (t / f"probe_{rev}.out").read_text()):
        rows.setdefault(int(k), {})[rev] = (name, h)
for k in sorted(rows):
    r = rows[k]; same = len({h for _, h in r.values()}) == 1
    note = "identical in rev1, rev2, rev3" if same else ("rev2 = rev3; rev1 differs (rev1 levels10 selected the archived generator; never run)" if r["rev2"][1] == r["rev3"][1] else "DIFFERENT")
    print(f"K={k:<5} rev1 {r['rev1'][0]:<22} {r['rev1'][1]}  rev2/rev3 {r['rev3'][0]:<23} {r['rev3'][1]}  {note}")
PY
grep -h "archived add" "$t"/probe_rev2.out "$t"/probe_rev3.out
GLEVELS_SEED=42 "$t/probe_rev3" | cmp -s - "$t/probe_rev3.out" && echo "rev3 with GLEVELS_SEED=42 generates the same inputs as with the variable unset"
